name: ralisaapp_pelabuhan
description: "RalisaApp Untuk Pelabuhan."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  http_parser: ^4.0.0
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  image_picker: ^1.0.4
  flutter_local_notifications: ^17.0.0
  flutter_background_service: ^5.0.1
  permission_handler: ^12.0.0+1
  device_info_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
